[DEFAULT]
kpi_kwargs = {
    "env_name": "ai4realnet_small",
    "acceptance_threshold": 200,
    "finetune_budget": 100000,
    "save_path": "results/ai4realnet_small"
    }

train_kwargs = {
    "model_name": "PPO_SB3",
    "train_steps": 1000,
    "save_freq": 5000,    
    "load_path": "trained_models/ai4realnet_small/PPO_SB3/PPO_SB3.zip",
    "save_path": "trained_models/ai4realnet_small/PPO_SB3_FINETUNE",
    }
    
eval_kwargs = {
    "n_eval_episodes": 50,
    "render": False,
    "deterministic": True,
    "return_episode_rewards": True,
    }

[EXPERT_AGENT]
kpi_kwargs = {
    "env_name": "ai4realnet_small",
    "acceptance_threshold": 200,
    "finetune_budget": 100000,
    "save_path": "results/ai4realnet_small/expert_agent"
    }

train_kwargs = {
    "train_steps": 5000,
    "n_eval_episodes": 2,
    "save_freq": 5000,    
    "load_path": "trained_models/ai4realnet_small/expert_agent/EXPERT_AGENT.zip",
    "save_path": "trained_models/ai4realnet_small/expert_agent/EXPERT_AGENT_FINETUNE",
    "load_path_fine_tune": "trained_models/ai4realnet_small/expert_agent/EXPERT_AGENT_FINETUNE/PPO_SB3.zip"
    }

eval_kwargs = {
    "nb_episode": 2,
    "verbose": True,
    "logs_path": "trained_models/ai4realnet_small/expert_agent/eval_logs",
    "nb_process": 1,
    }
; eval_kwargs = {
;     "n_eval_episodes": 50,
;     "render": False,
;     "deterministic": True,
;     "return_episode_rewards": True,
;     "logs_path": "trained_models/ai4realnet_small/expert_agent"
;     }